version: "3"
services:
  web:
    build: .
    volumes:
      - .:/app
    depends_on:
      - firefox
    environment:
      - REMOTE_FIREFOX=http://firefox:4444
      - CHANGJIANG_USER=BASE111
      - CHANGJIANG_PASSWORD=BASE111
      - CSRFTOKEN=game5adoeQpnUuXBKM0SiFDJhvWl3efc
      - SESSIONID=fqz31bjy28gug4m0z6rocoys82izh4mv
  firefox:
    image: selenium/standalone-firefox:latest
    ports:
      - "4444:4444"