version: "3"
services:
  web:
    build: .
    volumes:
      - .:/app
    depends_on:
      - firefox
    environment:
      - REMOTE_FIREFOX=http://firefox:4444
      - CHANGJIANG_USER=
      - CHANGJIANG_PASSWORD=
      - CSRFTOKEN=
      - SESSIONID=
  firefox:
    image: selenium/standalone-firefox:latest
    ports:
      - "4444:4444"